# create report
# dont forget, you need to sign in first.
# What Does the 403 Forbidden Error Mean? The HTTP status code '403 forbidden—you don't have permission to access this resource' is displayed when a web server recognizes a user's request but is unable to allow additional access.
POST http://localhost:5000/reports
Content-Type: application/json

{
    "make": "ford",
    "model": "mustang",
    "year": 1982,
    "mileage": 50000,
    "lng":45,
    "lat":45,
    "price":20000
}

### Approve an existing report
PATCH http://localhost:5000/reports/25
Content-Type: application/json

{
    "approve": true
}

### Get an estimate for an exsiting report 
# GET http://localhost:5000/reports?make=Toyotaa&model=Corolla&year=1981&lng=0&lat=0&mileage=100000
# GET http://localhost:5000/reports?make=ford&model=mustang&year=1981&lng=45&lat=45&mileage=50000
# GET http://localhost:5000/reports?make=ford&model=mustang&year=1985&lng=41&lat=46&mileage=45000
GET http://localhost:5000/reports?make=ford&model=mustang&year=1978&lng=41&lat=46&mileage=45000